// --- Eksisterende problemer (fra Firestore, hentet med scripts/inspect-problems.ts) ---
export const PROBLEMS: Record<string, string> = {
  hoste: "vdpeg0x3Rm9UA1GGxEAW",
  "vond-hals": "bu0BFQA6yxJuEXzMBaZV",
  forkjolelse: "bQFULJfyjTZSgkfm9sDd",
  hodepine: "GMfnNReM0ekDRbjynnxf",
  sovnproblemer: "SytG9jE1NcfsTREXq2de",
  myggstikk: "MsNtERMw7CaFCz35Mn59",
  "forstuet-fot": "zMCqA3OTXVc8WpyrJ3Yu",
};

// --- Tradisjonelle kjerringråd / husråd per plage ---
// Beskrivelsene presenterer rådene som tradisjonell/folkelig kunnskap, ikke medisinsk dokumentert behandling.
export const REMEDIES: Record<string, { title: string; description: string }[]> = {
  hoste: [
    { title: "Honning og varm melk", description: "Et glass varm melk med en skje honning før sengetid. Et av de mest kjente kjerringrådene mot hoste, brukt i generasjoner." },
    { title: "Løksaft", description: "Skiver av løk lagt i sukker over natten, sevjen som dannes drikkes med en skje. Sterk smak, men et klassisk husråd." },
    { title: "Ingefærte med sitron", description: "Fersk ingefær kokt i vann, med sitron og honning i. Varmende drikke som mange sverger til ved hoste." },
    { title: "Tymian-te", description: "Tørket tymian trukket i kokende vann i ti minutter. Brukt tradisjonelt for å lindre kraftig hoste." },
    { title: "Damp fra varmt vann", description: "Sitte over en bolle med varmt vann og et håndkle over hodet, puste inn dampen. Gammelt husråd mot tett hoste." },
    { title: "Saltvannsgurgling", description: "En teskje salt oppløst i varmt vann, gurgle flere ganger om dagen. Enkelt og mye brukt husråd." },
    { title: "Eddikomslag på brystet", description: "Et håndkle dyppet i varm eddikblanding lagt på brystet. Et eldre kjerringråd som færre kjenner til i dag." },
    { title: "Rå hvitløk", description: "En fedd hvitløk knust og svelget, eventuelt blandet med honning. Kraftig smak, lenge brukt mot luftveisplager." },
    { title: "Varm sitronsaft med honning", description: "Saften av en hel sitron i varmt vann med honning. Mild og mye brukt variant for både hoste og sår hals." },
    { title: "Pepperrot og honning", description: "Revet pepperrot blandet med honning, en liten skje tatt om dagen. Sterkt husråd fra eldre tradisjon." },
    { title: "Varm fennikel-te", description: "Fennikelfrø trukket i varmt vann. Brukt tradisjonelt for å løse opp slim ved hoste." },
    { title: "Brystsalve med kamfer", description: "Salve gnidd inn på brystet før sengetid, gjerne under et ullundertøy. Klassisk fra eldre generasjoner." },
    { title: "Varm rødvin med krydder", description: "Litt oppvarmet rødvin med kanel og nellik. Brukt mer som et eldre voksenrettet husråd mot hoste på kvelden." },
    { title: "Tyttebærsaft", description: "Ublandet tyttebærsaft drukket lunken. Norsk husråd brukt mot hoste og forkjølelse i generasjoner." },
    { title: "Karamellisert sukker i varmt vann", description: "Sukker smeltet gyllenbrunt og rørt ut i varmt vann. Eldre husråd som skal lindre en irritert hals ved hoste." },
  ],
  "vond-hals": [
    { title: "Saltvannsgurgling", description: "Varmt vann med en teskje salt, gurgle i ti-femten sekunder flere ganger daglig. Et av de mest brukte husrådene mot sår hals." },
    { title: "Honning og sitron", description: "En skje honning rørt ut i varmt vann med litt sitronsaft. Mild og lindrende, populært husråd." },
    { title: "Varm kamillete", description: "Kamilleblomster trukket i varmt vann, gjerne med honning. Brukt for å roe en irritert hals." },
    { title: "Ingefær og honning", description: "Fersk ingefær i varmt vann med honning. Varmende og mye brukt mot sårhet i halsen." },
    { title: "Eddik og vann-gurgling", description: "Eplecidereddik blandet med varmt vann, brukt til gurgling. Eldre husråd, sterk smak men trofaste brukere." },
    { title: "Varm melk med gurkemeie", description: "Et glass varm melk med en klype gurkemeie. Husråd med opphav i indisk folkemedisin, populært også her." },
    { title: "Lakrisrot-te", description: "Lakrisrot trukket i vann. Tradisjonelt brukt for å lindre en sår og tørr hals." },
    { title: "Halstabletter med salvie", description: "Salvieblader tygget eller trukket som te. Et eldre, mindre kjent husråd for halsbesvær." },
    { title: "Varm buljong", description: "En kopp varm kyllingbuljong eller grønnsaksbuljong. Enkelt husråd som mange foreldre bruker på barn." },
    { title: "Fuktet luft om natten", description: "En bolle vann ved sengen eller en luftfukter på rommet. Hjelper mot at halsen blir ekstra sår av tørr luft." },
    { title: "Sitron og pepper", description: "Varmt vann med sitronsaft og en klype cayennepepper. Sterkere variant brukt av noen for å 'brenne bort' irritasjonen." },
    { title: "Hvitløk i varm buljong", description: "Knust hvitløk rørt inn i varm buljong. Kombinerer to klassiske husråd i ett." },
    { title: "Varm rosin-avkok", description: "Rosiner kokt i vann til en søt, varm drikk. Eldre husråd brukt for å lindre en sår hals." },
    { title: "Fersk ingefær tygget", description: "En liten skive ingefær tygget sakte. Brukes for å varme og roe halsen." },
    { title: "Eukalyptus-inhalasjon", description: "Eukalyptusolje i varmt vann, puste inn dampen. Tradisjonelt brukt mot hovne slimhinner i halsen." },
  ],
  forkjolelse: [
    { title: "Hvitløk og honning", description: "Knust rå hvitløk blandet med honning, tatt en skje om dagen. Klassisk kjerringråd, tradisjonelt brukt for å lindre symptomer ved forkjølelse." },
    { title: "Varm ingefærte", description: "Fersk ingefær kokt i vann med sitron og honning. Et av de mest brukte rådene ved begynnende forkjølelse." },
    { title: "Varm kyllingsuppe", description: "Hjemmelaget kyllingsuppe med grønnsaker. Et husråd som går igjen i mange kulturer mot forkjølelse." },
    { title: "C-vitamin fra appelsin og sitron", description: "Rikelig med sitrusfrukter de første dagene. Tradisjonelt råd for å støtte kroppen gjennom en forkjølelse." },
    { title: "Løk i sokken", description: "Skiver av rå løk lagt i sokkene over natten. Et eldre og noe omstridt kjerringråd, men fortsatt brukt av noen." },
    { title: "Varm dusj med eukalyptus", description: "Noen dråper eukalyptusolje i en varm dusj, puste inn dampen. Brukt for å lette tett nese." },
    { title: "Mye hvile og varme drikker", description: "Holde seg varm, drikke te og hvile mye de første dagene. Enkelt, men det mest grunnleggende husrådet av alle." },
    { title: "Saltvannsskylling av nesen", description: "Lett saltvannsløsning brukt til å skylle nesen. Husråd for å løse opp slim og lette pusten." },
    { title: "Varm honning- og ingefærshot", description: "Konsentrert blanding av ingefær, honning og sitron tatt som en 'shot'. Populært i nyere tid, men bygger på gamle ingredienser." },
    { title: "Varme fotbad", description: "Føttene i varmt vann en stund før sengetid. Et eldre husråd som skal hjelpe kroppen å 'svette ut' forkjølelsen." },
    { title: "Tørket hyllebær-te", description: "Hyllebær trukket i varmt vann. Et tradisjonelt nordisk husråd brukt ved forkjølelse og influensa." },
    { title: "Rå ingefær tygget", description: "En liten skive fersk ingefær tygget direkte. Sterkt på smak, men mange opplever det som lindrende." },
    { title: "Varmt sjal og ullsokker", description: "Holde kroppen varm med ull innendørs. Gammelt husråd om at kulde 'forsinker' bedring." },
    { title: "Varm rosin- og nype-te", description: "Nyper og rosiner trukket i varmt vann. Norsk husråd rikt på C-vitamin, brukt mot forkjølelse." },
    { title: "Sennepsplaster på brystet", description: "Et tynt lag sennepspasta lagt på et tøystykke mot brystet en kort stund. Eldre og sterkere husråd, brukt med forsiktighet." },
  ],
  hodepine: [
    { title: "Pepperminteolje på tinningene", description: "Et par dråper pepperminteolje massert inn på tinningene. Mye brukt husråd mot spenningshodepine." },
    { title: "Kaldt omslag i nakken", description: "Et kaldt, fuktig håndkle lagt i nakken eller på pannen. Enkelt og tradisjonelt husråd." },
    { title: "Mørkt rom og stillhet", description: "Ligge i et mørkt og stille rom en stund. Et av de eldste og mest grunnleggende rådene mot hodepine." },
    { title: "Rikelig med vann", description: "Drikke et par glass vann med en gang hodepinen merkes. Husråd basert på at lett dehydrering ofte er årsaken." },
    { title: "Ren ingefærte mot hodepine", description: "Fersk ingefær trukket i varmt vann. Tradisjonelt brukt mot hodepine forbundet med kvalme." },
    { title: "Nakkemassasje med varme hender", description: "Lett massasje av nakke og skuldre. Et husråd som går på å løse opp muskelspenning som ofte ligger bak hodepinen." },
    { title: "Varm dusj på nakken", description: "Lunkent til varmt vann rettet mot nakken i dusjen. Brukt for å slappe av stramme muskler." },
    { title: "Lavendelolje på pannen", description: "Et par dråper lavendelolje gnidd inn på pannen. Eldre husråd, ofte brukt sammen med ro og mørke." },
    { title: "Kaffe i moderate mengder", description: "En liten kopp kaffe ved begynnende hodepine. Husråd som bygger på koffeinens kjente effekt på blodårer." },
    { title: "Klut med eddik på pannen", description: "Et håndkle dyppet i kald eddikblanding lagt på pannen. Eldre og mindre kjent kjerringråd." },
    { title: "Akupressur mellom tommel og pekefinger", description: "Trykke fast på punktet mellom tommel og pekefinger noen minutter. Tradisjon hentet fra folkemedisin." },
    { title: "Eplecidereddik i vann", description: "En skje eplecidereddik i et glass vann. Husråd som noen bruker mot hodepine forbundet med fordøyelsen." },
    { title: "Kald klut på pulsene", description: "En kald, fuktig klut lagt på innsiden av håndleddene. Eldre husråd for å 'kjøle ned' kroppen ved hodepine." },
    { title: "Spise noe smått", description: "Et lite måltid eller frukt ved hodepine. Husråd basert på at lavt blodsukker ofte er medvirkende." },
    { title: "Frisk luft og en kort spasertur", description: "Gå en runde ute i frisk luft. Enkelt husråd som mange opplever lindrer en mild hodepine." },
  ],
  sovnproblemer: [
    { title: "Varm melk med honning", description: "Et glass varm melk med en skje honning før sengetid. Et av de eldste kjerringrådene for å sovne lettere." },
    { title: "Kamillete på kvelden", description: "Kamilleblomster trukket i varmt vann en time før sengetid. Brukt i generasjoner for å roe ned før søvn." },
    { title: "Lavendelolje på pute eller pulsene", description: "Et par dråper lavendelolje på puten. Tradisjonelt husråd for å gjøre rommet mer søvnvennlig." },
    { title: "Fast leggetid hver kveld", description: "Legge seg og stå opp til samme tid hver dag. Enkelt, men ofte undervurdert husråd for bedre søvn." },
    { title: "Ingen skjermer en time før sengetid", description: "Legge bort telefon og skjermer i god tid før man legger seg. Nyere, men mye anbefalt råd." },
    { title: "Varmt bad om kvelden", description: "Et varmt bad 1-2 timer før sengetid. Husråd som bygger på at kroppstemperaturen som faller etterpå gjør en trøtt." },
    { title: "Pusteøvelser i sengen", description: "Rolig pusting, for eksempel fire sekunder inn og seks ut. Eldre teknikk brukt for å roe nervesystemet." },
    { title: "Lukket sovende rom, kjølig temperatur", description: "Holde sovrommet kjølig og mørkt. Tradisjonelt råd om at et kjølig rom gir bedre søvn." },
    { title: "Te av humle og baldrian", description: "Humle- og baldrianrot trukket som te. Eldre nordisk husråd brukt spesielt mot uro før sengetid." },
    { title: "Skrive ned tanker før sengetid", description: "Notere ned det som ligger i hodet i en liten bok. Brukt for å unngå at tankene kverner når man skal sove." },
    { title: "Tung dyne eller pledd", description: "Sove under en tyngre dyne enn vanlig. Husråd som mange opplever gir en roligere natt." },
    { title: "Magnesium-rikt kveldsmåltid", description: "Litt nøtter eller banan før sengetid. Husråd som bygger på at magnesium skal gjøre kroppen mer avslappet." },
    { title: "Lyd av regn eller hvit støy", description: "Rolig bakgrunnslyd på rommet. Brukes tradisjonelt for å dekke over plutselige lyder som vekker en." },
    { title: "Lett strekkøvelser før sengetid", description: "Noen rolige tøyninger i nakke og rygg. Eldre husråd for å løse opp spenninger før man legger seg." },
    { title: "Lavendelpute under hodepuden", description: "En liten pute med tørket lavendel lagt under hovedputen. Tradisjonelt brukt for å roe sinnet før søvn." },
  ],
  myggstikk: [
    { title: "Eddik på stikket", description: "Litt eplecidereddik dabbet på stikket med en bomullsdott. Klassisk husråd mot kløe etter myggstikk." },
    { title: "Bakepulver-pasta", description: "Bakepulver blandet med litt vann til en pasta, smøres på stikket. Mye brukt husråd for å dempe kløen." },
    { title: "Honning på stikket", description: "En liten klatt honning lagt rett på stikket. Eldre husråd som skal lindre irritasjonen." },
    { title: "Kald gjenstand mot huden", description: "En kald skje eller isbit holdt mot stikket et minutt. Enkelt og raskt husråd mot kløe og hevelse." },
    { title: "Aloe vera-gel", description: "Gel fra et aloe vera-blad smurt på stikket. Tradisjonelt brukt for å kjøle og lindre huden." },
    { title: "Tea tree-olje fortynnet", description: "Noen dråper tea tree-olje blandet med en bæreolje, dabbet på stikket. Husråd hentet fra australsk folkemedisin." },
    { title: "Sitronskall gnidd på huden", description: "Innsiden av et sitronskall gnidd direkte på stikket. Eldre husråd, frisk lukt og mild lindring." },
    { title: "Salt og vann-pasta", description: "Salt blandet med litt vann til en tykk pasta. Husråd som skal trekke ut hevelse fra stikket." },
    { title: "Basilikumblader knust mot huden", description: "Friske basilikumblader knust lett og gnidd på stikket. Mindre kjent, men brukt i flere matlagingskulturer." },
    { title: "Lavendelolje", description: "Et par dråper lavendelolje på stikket. Brukes både for duft og en mild kjølende effekt." },
    { title: "Løkskive på stikket", description: "En tynn skive rå løk lagt på stikket noen minutter. Gammelt og noe ukjent husråd utenfor distriktene." },
    { title: "Banan-skall gnidd på stikket", description: "Innsiden av et bananskall gnidd på stikket. Mindre kjent, men brukt husråd for å dempe kløe." },
    { title: "Eddiksoaket bomullsdott", description: "En bomullsdott fuktet med eddik holdt mot stikket noen minutter. Husråd som skal kjøle og lindre." },
    { title: "Kald melkeklut", description: "Et tøystykke dyppet i kald melk lagt på stikket. Eldre, lite kjent husråd mot kløe." },
    { title: "Tannkrem på stikket", description: "Litt mentolholdig tannkrem dabbet på stikket. Husråd kjent for den kjølende mentol-effekten." },
  ],
  "forstuet-fot": [
    { title: "Hvile, is, kompresjon, elevasjon (RICE)", description: "Hvile foten, kjøling med is, en stram bandasje og foten høyt. Den mest etablerte 'husrådvarianten' av førstehjelp ved forstuing." },
    { title: "Iskompress de første 48 timene", description: "Is pakket i et håndkle lagt på foten i 15-20 minutter i strekk. Klassisk råd for å dempe hevelse rett etter skaden." },
    { title: "Kald eddikomslag", description: "Et håndkle dyppet i kaldt vann med litt eddik, lagt rundt foten. Eldre husråd brukt mot hevelse og verk." },
    { title: "Elevere foten på en pute", description: "Ligge med foten høyere enn hjertet store deler av dagen. Tradisjonelt råd for å redusere oppsamling av væske." },
    { title: "Varm gurkemeie-omslag (etter de første dagene)", description: "Gurkemeie blandet til en pasta, lagt på foten når akutt hevelse har gått ned. Husråd hentet fra indisk folkemedisin." },
    { title: "Epsom-saltbad", description: "Foten i varmt vann med epsom-salt, brukt noen dager etter skaden. Eldre husråd for å lindre stivhet." },
    { title: "Arnika-salve", description: "Salve med arnika gnidd inn rundt det forstuede området. Tradisjonelt plantebasert husråd mot støtskader." },
    { title: "Kålblad-omslag", description: "Friske kålblader lett knust og lagt rundt foten, holdt på plass med en bandasje. Gammelt nordisk husråd mot hevelse." },
    { title: "Lett støtte med teip", description: "Sportsteip lagt rundt ankelen for ekstra støtte under lett belastning. Husråd brukt av idrettsfolk i generasjoner." },
    { title: "Varmt fotbad etter den akutte fasen", description: "Varmt vann etter de første dagene, når hevelsen har gått ned. Skal bedre blodsirkulasjonen og stivheten." },
    { title: "Bandasje med kald gel-pakning", description: "En gel-pakning surret rundt foten med en elastisk bandasje. Husråd for å kombinere kulde og lett kompresjon." },
    { title: "Ingefær-omslag (etter akutt fase)", description: "Revet ingefær lagt i et tøystykke mot foten etter de første dagene. Tradisjonelt brukt for å øke blodsirkulasjon." },
    { title: "Lett tøying av ankelen", description: "Rolige sirkelbevegelser med foten når smerten tillater det. Eldre råd for å unngå stivhet under tilheling." },
    { title: "Eddik- og saltvannsbad", description: "Foten i lunkent vann med litt eddik og salt. Husråd brukt noen dager etter skaden for å dempe verk." },
    { title: "Avlastning med stokk eller krykke", description: "Bruke støtte for å avlaste foten de første dagene. Eldre og praktisk husråd for å unngå ny belastning før tilheling." },
  ],
};

// --- Kommentarmaler for å lage realistiske erfaringer ---
export const POSITIVE_COMMENTS = [
  "Fungerte virkelig bra for meg!",
  "Ble merkbart bedre etter dette.",
  "Brukte dette i flere dager, hjalp godt.",
  "Overrasket over hvor bra dette virket.",
  "Det gamle husrådet holder stand, dette hjalp.",
  "Lindret godt, kommer til å bruke dette igjen.",
  "Anbefales, hjalp raskere enn jeg trodde.",
  "Min mormor lærte meg dette, virker fortsatt.",
  "Effekten kom ganske raskt, ble fornøyd.",
  "Dette er blitt min faste rutine nå.",
  "Hjalp barnet mitt også, lett å bruke.",
  "Litt skeptisk i starten, men ble positivt overrasket.",
];

export const NEUTRAL_OR_NEGATIVE_COMMENTS = [
  "Hjalp litt, men ikke noe stort under.",
  "Merket ingen tydelig effekt for min del.",
  "Kanskje placebo, men kjentes greit ut.",
  "Fungerte dårligere enn jeg hadde forventet.",
  "Måtte kombinere med annet for å merke noe.",
  "Lukten/smaken var verre enn nytten.",
  "Ingen effekt etter flere forsøk.",
  "Litt usikker på om det egentlig gjorde noe.",
  "Virket bare svakt og kort.",
  "Forventet mer, ble litt skuffet.",
];
